name: Compile and Release Latex  PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile document.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: resume_en.tex

      - name: Publish LaTeX
        uses: actions/upload-artifact@v4
        with:
          path: |
            resume_en.tex
            resume_ru.tex