name: Compile Latex and Release PDF

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*.*'
      - '*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Build LaTeX
        run: |
          for project in $(ls); do
          if [ -d "$project" ]; then
           cd ${project}
           latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=$PWD/../ $PWD/${project}
           cd ..
          fi
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./resume_en.pdf
            ./resume_ru.pdf
