name: Compile and Release Latex  PDF

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile document.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: '*.tex'

      - name: Publish LaTeX
        run : |
          git config --global user.email "ermolenkoav@gmail.com"
          git config --global user.name "Alexey Ermolenko"
          git add -f $PWD/*.pdf
          git commit -m "WORKFLOW_COMMIT - Update PDFs [skip ci]"
          git push
