name: Compile and Release Latex  PDF

on:
  push:
    tags:
      - '*.*'
      - 'ver.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Build LaTeX
        run: |
          for project in $(ls); do
          if [ -d "$project" ]; then
           cd ${project}
           latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=$PWD/../ $PWD/${project}
           cd ..
          fi
          done
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: | 
            ./CurriculumVitae/out/resume_*.pdf
            ./CurriculumVitae/resume_*.pdf
